name: nps_sdk
description: API with which you can interact with NPS's platform.
version: 0.0.8
author: IngenicoNpsLatam <development@sub1.com.ar>
homepage: https://github.com/Ingenico-NPS-Latam/nps-sdk-dart
documentation: https://developers.nps.com.ar/

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: "^0.11.3+16"
  xml: "^3.0.0"
  xml2json: "^2.0.13"

dev_dependencies:
  test: ^0.12.0
