name: nps_sdk
description: API with which you can interact with NPS's platform.
version: 1.0.0
author: IngenicoNpsLatam <development@sub1.com.ar>
homepage: https://github.com/Ingenico-NPS-Latam/nps-sdk-dart
documentation: https://developers.nps.com.ar/

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  http: '^0.11.3+17' 
  xml: '^3.2.0'
  xml2json: '^3.0.1'
 
